version: "3"

# https://docs.mongodb.com/manual/reference/connection-string/

services:
  nodeosd:
    #build:
    #  context: . # Uses ./Dockerfile
    image: eosio/eos-dev:v1.2.4
    command: >
      /opt/eosio/bin/nodeosd.sh
      --contracts-console
      --data-dir /opt/eosio/bin/data-dir
      -e
      # --mongodb-wipe --mongodb-uri mongodb://mongodb:27017/EOS
      --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
      --http-validate-host=false
      --access-control-allow-origin "*"
      --verbose-http-errors
      --filter-on=*
    hostname: nodeosd
    restart: always
    # links:
    #   - mongodb
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ../:/eosio # data for cleos set contract, etc..
    stop_grace_period: 10m

  keosd:
    image: eosio/eos-dev:v1.2.4
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900
    hostname: keosd
    restart: always
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ../:/eosio # data for cleos set contract, etc..
    stop_grace_period: 10m

  # mongodb:
  #   image: mongo:4.0
  #   hostname: mongodb
  #   volumes:
  #     - mongodb:/data/db
  #     - mongodb_config:/data/configdb
  #   ports:
  #       - 27017:27017
  #   command: mongod

volumes:
  nodeos-data-volume:
    external: false
  keosd-data-volume:
    external: false
  # mongodb:
  # mongodb_config:
